
---
*/
/*
### Try Service: 'workflows' (http://localhost:9090/workflows)

*/
/*
#### POST /approval/signal

*/
###
POST http://localhost:9090/workflows/approval/signal
Content-Type: */*

{
    "requestId": "REQ-002",
    "signalName": "approved",
    "comment": "approved by manager"
  }

HTTP/1.1 500  - Internal Server Error
content-type: application/json
connection: close
server: ballerina
date: Wed, 10 Dec 2025 15:15:40 +0530
content-encoding: gzip
content-length: 191
###
POST http://localhost:9090/workflows/approval
Content-Type: */*

{
    "requestId": "REQ-DIRECT-001",
    "amount": 500,
    "requester": "user@example.com"
  }

HTTP/1.1 201  - Created
content-type: application/json
connection: close
server: ballerina
date: Thu, 11 Dec 2025 16:07:51 +0530
content-encoding: gzip
content-length: 119
###
GET http://localhost:9090/workflows/health